### PR TITLE
CMake integration.

### PR DESCRIPTION
**Pull request by evo-i**
Need more time for support tests...

### CODE REVIEW

**Comment by evo-i** [comment]
@johang Hi, no way to implement test environment with current binaries, cuz no way to check return code from e.g. `vlcdummy`.
So maybe need to use some test framework?

**Comment by evo-i** [comment]
Only what i get from the test it is output like this:
```
VLCDUMMY ITEM 18945a9300abfe4ff2442559bb08b8ddb357c16f.torrent
VLCDUMMY STATE 18945a9300abfe4ff2442559bb08b8ddb357c16f.torrent OPENING
VLCDUMMY STATE 18945a9300abfe4ff2442559bb08b8ddb357c16f.torrent PLAYING
VLCDUMMY SUBITEM flags (DIRECTORY)
VLCDUMMY SUBITEM denmark.png (FILE)
VLCDUMMY SUBITEM norway.png (FILE)
VLCDUMMY SUBITEM sweden.png (FILE)
VLCDUMMY STATE 18945a9300abfe4ff2442559bb08b8ddb357c16f.torrent ENDED (0 audio frames, 0 video frames)
VLCDUMMY END
```

**Comment by johang** [comment]
I don't mind if you change the tests to use some framework.

**Comment by evo-i** [comment]
> I don't mind if you change the tests to use some framework.

Good, so later i will add some commit.

**Comment by evo-i** [comment]
Sorry guys, no way to compile on Windows, so I'll create a new repository for Windows...
With optimized code for compiling on this OS.
However, I'll work on `CMake` support, and soon I'll add a full-fledged `CMakeLists.txt`, as well as `GTest` support for the test environment.

**Comment by evo-i** [comment]
I have an idea, maybe need to put  all vlc stuff to be internal, and this can fix problems with windows sdk VLC.

**Comment by johang** [comment]
I merged parts of your patch. It has very basic CMake support. Let's skip the tests for now.

**Pull request closed without merging**
