### PR TITLE
Remove downloaded temporary files when exiting VLC.

### LINKED ISSUE #10: Remove temporary file when vlc exits?
When exiting vlc after playing a torrent, the .parts file is left on disk.  Perhaps it is better to remove it when vlc exits, to avoid filling up the disk with temp files?

### PR DESCRIPTION
**Pull request by petterreinholdtsen**
Fixes #10.

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
I've included this patch in the Debian package.  Please let me know if you believe it was a bad idea.

**Comment by johang** [comment]
There's some bug when closing the session that makes libtorrent crash. That's why I have a small sleep there. This patch triggers that bug again. That's why the tests fail. I can't merge this when the tests fail.

I have plans to rewrite download.cpp (and fix #13 at the same time).

**Comment by petterreinholdtsen** [comment]
Aha.  The tests fail all the time here, so I assumed it was the normal state of affairs.  Is the libtorrent crash bug reported to the libtorrent developers?  Do you have a URL to the bug report?

**Comment by johang** [comment]
Fixed in 5d4fda9.

**Pull request closed without merging**
