### PR TITLE
Make playlist ordering predictable by sorting files on size, largest first.

### PR DESCRIPTION
**Pull request by petterreinholdtsen**

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
I've included this patch in the Debian package.  Please let me know if you believe it was a bad idea.

**Comment by petterreinholdtsen** [comment]
Is there something wrong with this patch I should know about?

**Comment by johang** [comment]
Yes, tests fail.

**Comment by petterreinholdtsen** [comment]
[Johan Gunnarsson]
> Yes, tests fail.

Here, the tests fail with and without the patch, so I am unsure what you
expect me to do about it.  Should I disable the unstable tests?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by johang** [comment]
The tests works and are fairly stable. Maybe you have other patches in your tree that breaks the tests?

**Comment by petterreinholdtsen** [comment]
At least part of the problem I tried to solve using this patch was caused by me having vlc set to pick a random file to play.  As the file ordering from the plugin now seem to be stable, I abandon this pull request.

**Pull request closed without merging**
